---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error
  template:
    metadata:
      labels:
        app: error
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: [ "/bin/bash", "-c" ]
          args:
            - |
            echo "crash"
